### ISSUE TITLE
A typo in Ubuntu suricata configure file

### ISSUE THREAD

**Issue by samhsu-dev** [jhu-information-security-institute/NwSec#1]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/35974430/160270534-bd7cc46b-8c51-4cca-9990-98fee64edc96.png">

Hi, the `ddos` may be a typo in `suricata-UbuntuServerX86-64.sh`, which should be dos. 

Best

**Comment by reubenajohnston** [comment]
corrected
